general {
    lock_cmd = quickshell -p ~/.config/hypr/scripts/quickshell/Lock.qml
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 6000
    on-timeout = loginctl lock-session
}

