#!/bin/bash
# plugin_install.sh — inspect <file.qsplugin> | install <file.qsplugin> | uninstall <id> | list
#
# .qsplugin = zip archive with manifest.json at root (or inside a single top dir):
#   {
#     "id":          "my-addon",            // required, ^[a-z0-9][a-z0-9._-]*$
#     "name":        "My Addon",
#     "version":     "1.0.0",
#     "description": "...",
#     "hypr":        "hypr.conf",           // optional: snippet sourced via addons.conf
#     "scripts":     ["scripts/foo.sh"],    // optional: chmod +x after install
#     "hooks":       { "install": "hooks/install.sh", "uninstall": "hooks/uninstall.sh" }
#   }
# Noctalia plugin fields (entry, settings, …) pass through untouched — the same
# manifest drives PluginLoader/PluginApplet for bar widgets.

set -u
PLUGINS_DIR="$HOME/.config/hypr/plugins"
ADDONS_CONF="$HOME/.config/hypr/addons.conf"
SCAN="$HOME/.config/hypr/scripts/scan_plugins.sh"
STAGING="/tmp/qs_plugin_staging"

die() { echo "ERROR: $*" >&2; exit 1; }

# Unpack archive to $STAGING and set $ROOT to the dir containing manifest.json
unpack() {
    local file="$1"
    [ -f "$file" ] || die "file not found: $file"
    rm -rf "$STAGING"; mkdir -p "$STAGING"
    unzip -qq "$file" -d "$STAGING" 2>/dev/null || die "not a valid zip archive"

    if [ -f "$STAGING/manifest.json" ]; then
        ROOT="$STAGING"
    else
        # zip of a folder → manifest one level down, require exactly one dir
        local dirs=( "$STAGING"/*/ )
        [ ${#dirs[@]} -eq 1 ] && [ -f "${dirs[0]}manifest.json" ] \
            || die "manifest.json not found in archive"
        ROOT="${dirs[0]%/}"
    fi
}

# Validate manifest in $ROOT, set $ID
validate() {
    jq -e . "$ROOT/manifest.json" >/dev/null 2>&1 || die "manifest.json is not valid JSON"
    ID="$(jq -r '.id // empty' "$ROOT/manifest.json")"
    [[ "$ID" =~ ^[a-z0-9][a-z0-9._-]*$ ]] || die "invalid or missing manifest id: '$ID'"

    # Declared paths must exist and stay inside the package
    local rel
    for rel in $(jq -r '[.hypr // empty,
                         .window // empty,
                         .desktopWidget // empty,
                         .cardSkin // empty,
                         (.entryPoints.barWidget // empty),
                         (.scripts // [])[],
                         (.hooks.install // empty),
                         (.hooks.uninstall // empty)] | .[]' "$ROOT/manifest.json"); do
        case "$rel" in
            /*|*..*) die "manifest path escapes package: $rel" ;;
        esac
        [ -f "$ROOT/$rel" ] || die "declared file missing from archive: $rel"
    done
}

# Rebuild addons.conf from all installed plugins that declare a hypr snippet
regen_addons_conf() {
    {
        echo "# Generated by plugin_install.sh — do not edit (regenerated on install/uninstall)"
        local m dir snippet
        for m in "$PLUGINS_DIR"/*/manifest.json; do
            [ -f "$m" ] || continue
            dir="$(dirname "$m")"
            snippet="$(jq -r '.hypr // empty' "$m" 2>/dev/null)"
            [ -n "$snippet" ] && [ -f "$dir/$snippet" ] && echo "source = $dir/$snippet"
        done
    } > "$ADDONS_CONF"
}

post_change() {
    regen_addons_conf
    hyprctl reload >/dev/null 2>&1
    [ -x "$SCAN" ] && "$SCAN" >/dev/null 2>&1
}

case "${1:-}" in
    inspect)
        unpack "$2"; validate
        # Manifest + computed summary for the install-confirmation UI
        jq --arg files "$(find "$ROOT" -type f | wc -l)" \
           --arg sizeKb "$(du -sk "$ROOT" | cut -f1)" \
           '. + {_files: ($files | tonumber), _sizeKb: ($sizeKb | tonumber),
                 _hasHypr:   (has("hypr")),
                 _hasHooks:  (has("hooks")),
                 _hasCardSkin: (has("cardSkin")),
                 _scriptCount: ((.scripts // []) | length),
                 _installed: false}' "$ROOT/manifest.json" \
        | jq --argjson inst "$( [ -d "$PLUGINS_DIR/$(jq -r .id "$ROOT/manifest.json")" ] && echo true || echo false )" \
             '. + {_installed: $inst}'
        ;;

    install)
        unpack "$2"; validate
        mkdir -p "$PLUGINS_DIR"
        rm -rf "${PLUGINS_DIR:?}/$ID"
        cp -r "$ROOT" "$PLUGINS_DIR/$ID"

        # chmod declared scripts + hooks
        while IFS= read -r rel; do
            [ -n "$rel" ] && chmod +x "$PLUGINS_DIR/$ID/$rel" 2>/dev/null
        done < <(jq -r '[(.scripts // [])[],
                         (.hooks.install // empty),
                         (.hooks.uninstall // empty)] | .[]' "$PLUGINS_DIR/$ID/manifest.json")

        hook="$(jq -r '.hooks.install // empty' "$PLUGINS_DIR/$ID/manifest.json")"
        if [ -n "$hook" ]; then
            ( cd "$PLUGINS_DIR/$ID" && bash "$hook" ) \
                || { rm -rf "${PLUGINS_DIR:?}/$ID"; post_change; die "install hook failed — rolled back"; }
        fi

        post_change
        rm -rf "$STAGING"
        echo "installed: $ID"
        ;;

    uninstall)
        ID="$2"
        [ -d "$PLUGINS_DIR/$ID" ] || die "not installed: $ID"
        hook="$(jq -r '.hooks.uninstall // empty' "$PLUGINS_DIR/$ID/manifest.json" 2>/dev/null)"
        if [ -n "$hook" ] && [ -f "$PLUGINS_DIR/$ID/$hook" ]; then
            ( cd "$PLUGINS_DIR/$ID" && bash "$hook" ) || echo "WARN: uninstall hook failed" >&2
        fi
        rm -rf "${PLUGINS_DIR:?}/$ID"
        post_change
        echo "uninstalled: $ID"
        ;;

    list)
        for m in "$PLUGINS_DIR"/*/manifest.json; do
            [ -f "$m" ] || continue
            jq -r '"\(.id)\t\(.version // "?")\t\(.name // .id)"' "$m"
        done
        ;;

    *)
        echo "Usage: $0 inspect <file> | install <file> | uninstall <id> | list" >&2
        exit 1
        ;;
esac
